### ISSUE TITLE
OPA1CON0: Bits 6 4 2 not used.

### ISSUE THREAD

**Issue by Ashdash-git** [microchip-pic-avr-examples/pic18f16q41-cnano-opamp-demo-fw#1]
Referring to application.c file, the 4 functions configuring the operational amplifier write the incorrect value to the OPA1CON0 register.  Bit 6 of the register is not implemented and reads as zero, yet is being written to.  I think the correct register values are as follows.

    void OPA_External(void) {
    ...
    **_OPA1CON0 = 0xC0; //EN Enabled; User Defined Feedback;_**
    OPA1CON0 = 0x80; //EN Enabled; User Defined Feedback;
    }

    void OPA_UnityGain(void) {
    ...
    _**OPA1CON0 = 0xC8; //EN Enabled; Unity Gain Connection Enabled;**_
    OPA1CON0 = 0x88; //EN Enabled; Unity Gain Connection Enabled;
    }

    void OPA_NonInverting(void) {
    ...
    **_OPA1CON0 = 0xC0; //EN Enabled; CPON Enabled; UG OPAIN- pin; SOC User Defined Feedback;_**
    OPA1CON0 = 0xA0; //EN Enabled; CPON Enabled; UG OPAIN- pin; SOC User Defined Feedback;
    }

    void OPA_Inverting(void) {
    ...
    **_OPA1CON0 = 0xC0; //EN Enabled; CPON Enabled; UG OPAIN- pin; SOC User Defined Feedback;_**
    OPA1CON0 = 0xA0; //EN Enabled; CPON Enabled; UG OPAIN- pin; SOC User Defined Feedback;
    }

**Comment by ashishmakthal** [comment]
@Ashdash-git We will look into this. Will get back to you shortly.

**Comment by jason-layton** [comment]
@Ashdash-git , thanks for bringing this to our attention. This bit in question that is causing the incorrect register value that you pointed out is the OPA Charge Pump Enable bit (CPON), which in this example shouldn't affect the functionality or demonstration if its disabled / enabled. We are however currently working on updating and correcting this in GitHub, and it should be resolved very soon. Thanks again!

**Comment by ashishmakthal** [comment]
@Ashdash-git v2.0.1 has the edits. Hope it helps!
